# Generated by Django 5.2.12 on 2026-04-05 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('natal', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_place',
            field=models.ForeignKey(blank=True, help_text='Default birth place for this user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_users', to='natal.place'),
        ),
    ]
