# Generated by Django 5.2.12 on 2026-04-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_default_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='onboarding_dismissed_at',
            field=models.DateTimeField(
                blank=True,
                help_text='When the user dismissed the onboarding wizard',
                null=True,
            ),
        ),
    ]
