# Generated by Django 5.2.12 on 2026-04-05 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name for the location', max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, help_text='Latitude in decimal degrees (-90 to 90)', max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, help_text='Longitude in decimal degrees (-180 to 180)', max_digits=9)),
                ('timezone', models.CharField(help_text="IANA timezone identifier (e.g., 'America/New_York')", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='User who created this place', on_delete=django.db.models.deletion.CASCADE, related_name='places', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'place',
                'verbose_name_plural': 'places',
                'db_table': 'natal_places',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NatalSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Descriptive name for this natal set', max_length=255)),
                ('birth_datetime', models.DateTimeField(help_text='Birth date and time')),
                ('notes', models.TextField(blank=True, default='', help_text='Optional notes about this natal chart')),
                ('permission', models.CharField(choices=[('private', 'Private'), ('named_group', 'Named Group'), ('public', 'Public')], default='private', help_text='Who can view this natal set', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='User who owns this natal set', on_delete=django.db.models.deletion.CASCADE, related_name='natal_sets', to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ManyToManyField(blank=True, help_text='Users with explicit access (for named_group permission)', related_name='shared_natal_sets', to=settings.AUTH_USER_MODEL)),
                ('place', models.ForeignKey(help_text='Birth location', on_delete=django.db.models.deletion.CASCADE, related_name='natal_sets', to='natal.place')),
            ],
            options={
                'verbose_name': 'natal set',
                'verbose_name_plural': 'natal sets',
                'db_table': 'natal_sets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='place',
            constraint=models.UniqueConstraint(fields=('name', 'created_by'), name='unique_place_name_per_user'),
        ),
    ]
