# Generated by Django 5.2.12 on 2026-04-06 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('natal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='natalset',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude in decimal degrees (-90 to 90)', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='natalset',
            name='location_name',
            field=models.CharField(blank=True, default='', help_text='Birth location name', max_length=255),
        ),
        migrations.AddField(
            model_name='natalset',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude in decimal degrees (-180 to 180)', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='natalset',
            name='timezone',
            field=models.CharField(blank=True, default='', help_text="IANA timezone identifier (e.g., 'America/New_York')", max_length=50),
        ),
        migrations.AlterField(
            model_name='natalset',
            name='place',
            field=models.ForeignKey(blank=True, help_text='Birth location', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='natal_sets', to='natal.place'),
        ),
    ]
