# Generated by Django 5.2.12 on 2026-04-06 22:09

from django.db import migrations


def _migrate_place_data(apps, schema_editor):
    """
    Copy location data from Place FK to inline fields on NatalSet.
    
    This preserves all existing natal set location data before the FK is removed.
    """
    NatalSet = apps.get_model('natal', 'NatalSet')
    
    updated_count = 0
    skipped_count = 0
    
    for natal_set in NatalSet.objects.select_related('place').all():
        if natal_set.place is not None:
            natal_set.location_name = natal_set.place.name
            natal_set.latitude = natal_set.place.latitude
            natal_set.longitude = natal_set.place.longitude
            natal_set.timezone = natal_set.place.timezone
            natal_set.save(update_fields=[
                'location_name', 'latitude', 'longitude', 'timezone'
            ])
            updated_count += 1
        else:
            skipped_count += 1
    
    # Print summary for observability
    print(f"Migrated {updated_count} natal sets from Place to inline fields")
    print(f"Skipped {skipped_count} natal sets with no place")


class Migration(migrations.Migration):

    dependencies = [
        ('natal', '0002_natalset_inline_location'),
    ]

    operations = [
        migrations.RunPython(
            _migrate_place_data,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
