# Generated by Django 5.2.12 on 2026-04-06 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('natal', '0003_auto_20260406_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='natalset',
            name='place',
        ),
    ]
