# Generated by Django 5.2.12 on 2026-04-08 00:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Descriptive name for this query', max_length=255)),
                ('query_type', models.CharField(choices=[('wedding', 'Wedding'), ('project', 'Project Launch'), ('travel', 'Travel Departure'), ('move_in', 'Move In'), ('medical', 'Medical Procedure'), ('other', 'Other')], default='other', help_text='Type of electional query', max_length=20)),
                ('query_params', models.JSONField(default=dict, help_text='Query parameters including location, date range, and preferences')),
                ('permission', models.CharField(choices=[('private', 'Private'), ('named_group', 'Named Group'), ('public', 'Public')], default='private', help_text='Who can view this query', max_length=20)),
                ('job_id', models.CharField(blank=True, default='', help_text='LLM backend job ID for tracking', max_length=100)),
                ('job_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Current job status', max_length=20)),
                ('job_error', models.TextField(blank=True, default='', help_text='Error message if job failed')),
                ('result_data', models.JSONField(blank=True, help_text='Results from the electional analysis', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='User who owns this query', on_delete=django.db.models.deletion.CASCADE, related_name='electional_queries', to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ManyToManyField(blank=True, help_text='Users with explicit access (for named_group permission)', related_name='shared_electional_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'saved query',
                'verbose_name_plural': 'saved queries',
                'db_table': 'electional_saved_queries',
                'ordering': ['-created_at'],
            },
        ),
    ]
