# Generated by Django 5.2.13 on 2026-04-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electional', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedquery',
            name='latitude',
            field=models.FloatField(default=0.0, help_text='Latitude of the query location (-90 to 90)'),
        ),
        migrations.AddField(
            model_name='savedquery',
            name='longitude',
            field=models.FloatField(default=0.0, help_text='Longitude of the query location (-180 to 180)'),
        ),
        migrations.AlterField(
            model_name='savedquery',
            name='query_params',
            field=models.JSONField(default=dict, help_text='Query parameters including date range and preferences'),
        ),
    ]
